In [94]:
import pandas as pd
import numpy as np
from copy import deepcopy

In [95]:
df=pd.read_csv("kknnn.csv")
df

x1   x2
0  3.2  5.9
1  2.9  4.6
2  2.8  6.2
3  3.2  4.7
4  4.2  5.5
5  3.0  5.0
6  3.1  4.9
7  3.1  6.7
8  3.8  5.1
9  3.0  6.0

In [96]:
x1=df["x1"].values
x2=df["x2"].values
x=np.array(list(zip(x1,x2)))
x

array([[3.2, 5.9],
       [2.9, 4.6],
       [2.8, 6.2],
       [3.2, 4.7],
       [4.2, 5.5],
       [3. , 5. ],
       [3.1, 4.9],
       [3.1, 6.7],
       [3.8, 5.1],
       [3. , 6. ]])

In [97]:
cy=[6.2,6.6,6.5]
cx=[3.2,3.7,3]
centroid=np.array(list(zip(cx,cy)))
centroid

array([[3.2, 6.2],
       [3.7, 6.6],
       [3. , 6.5]])

In [98]:
oldcentroid=np.zeros(centroid.shape)

oldcentroid

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [99]:
scluster=np.zeros(len(x))
scluster

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [100]:
def euclidean(a,b,ax=1):
    return np.linalg.norm(a-b,axis=ax)


In [101]:
error=euclidean(centroid,oldcentroid,None)
error

12.53714481052205

In [102]:
k=3
itter=0
while error!=0:
    itter=itter+1
    for i in range (len(x)):
        distance=euclidean(x[i],centroid)
        cluster=np.argmin(distance)
        scluster[i]=cluster
    oldcentroid=deepcopy(centroid)
    print("old centroid",oldcentroid)
        
    for p in range (k):
        points=[x[j] for j in range (len(x)) if scluster[j]==p]
        centroid[p]=np.mean(points,axis=0)
    print("centroid after ",itter, "is",centroid)
    error=euclidean(centroid,oldcentroid,None)
    print(error)
    print("datapoints belong to cluster",scluster)
    


old centroid [[3.2 6.2]
 [3.7 6.6]
 [3.  6.5]]
centroid after  1 is [[3.17142857 5.17142857]
 [4.2        5.5       ]
 [2.95       6.45      ]]
1.588639515498743
datapoints belong to cluster [0. 0. 2. 0. 1. 0. 0. 2. 0. 0.]
old centroid [[3.17142857 5.17142857]
 [4.2        5.5       ]
 [2.95       6.45      ]]
centroid after  2 is [[3.05  4.8  ]
 [4.    5.3  ]
 [3.025 6.2  ]]
0.5484788798419251
datapoints belong to cluster [2. 0. 2. 0. 1. 0. 0. 2. 1. 2.]
old centroid [[3.05  4.8  ]
 [4.    5.3  ]
 [3.025 6.2  ]]
centroid after  3 is [[3.05  4.8  ]
 [4.    5.3  ]
 [3.025 6.2  ]]
0.0
datapoints belong to cluster [2. 0. 2. 0. 1. 0. 0. 2. 1. 2.]
